"""
Post-processing script for OpenFOAM
"""

import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
from scipy.signal import find_peaks
from scipy.fft import fft, fftfreq

# ============================================================
# CONFIGURATION
# ============================================================

# Use absolute paths to avoid directory issues
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
# Path to OpenFOAM force coefficients file
FORCES_FILE = os.path.join(BASE_DIR, "forces", "0.1", "coefficient_steady.dat")
# Path to logs directory generated by 'foamLog'
CASE_ROOT = os.path.abspath(os.path.join(BASE_DIR, ".."))
LOGS_DIR = os.path.join(CASE_ROOT, "logs")
# Output directory for plots
OUTPUT_DIR = os.path.join(BASE_DIR, "plots")

# Physical parameters
T_START = 0.1       # Steady-state threshold time (s)
L_REF = 0.2         # Characteristic length (Diameter) (m)
U_INF = 30          # Free-stream velocity (m/s)
SIGNAL_NAME = "Cl"  # Signal used for vortex shedding analysis

if not os.path.exists(OUTPUT_DIR):
    os.makedirs(OUTPUT_DIR)

# ============================================================
# RESIDUALS ANALYSIS (Convergence)
# ============================================================

def plot_residuals(log_dir=LOGS_DIR):
    """Reads foamLog output files and plots solver convergence."""
    fields = ['Ux_0', 'Uy_0', 'p_0', 'k_0', 'omega_0']
    plt.figure(figsize=(10, 6))
    
    found_any = False
    for field in fields:
        file_path = os.path.join(log_dir, field)
        if os.path.exists(file_path):
            data = pd.read_csv(file_path, sep='\t', header=None, names=['Time', 'Val'])
            plt.semilogy(data['Time'], data['Val'], label=field.split('_')[0])
            found_any = True
    
    if found_any:
        plt.title('Solver Convergence (Residuals)')
        plt.xlabel('Iterations / Time')
        plt.ylabel('Residual (Log Scale)')
        plt.grid(True, which="both", ls="-", alpha=0.5)
        plt.legend()
        plt.savefig(os.path.join(OUTPUT_DIR, "residuals_convergence.png"), dpi=300)
        print(f"Success: Residuals plot saved to {OUTPUT_DIR}")
    else:
        print(f"Warning: No residual logs found in {log_dir}. Did you run 'foamLog log.pimpleFoam'?")
    plt.close()

# ============================================================
# COEFFICIENTS & FREQUENCY ANALYSIS
# ============================================================

def process_coefficients(file_path=FORCES_FILE):
    """Analyzes force coefficients, computes FFT and Strouhal number."""
    if not os.path.exists(file_path):
        print(f"Error: Force file not found at {file_path}")
        return

    # Load data skipping headers
    df = pd.read_csv(file_path, sep='\s+', comment='#', header=None)
    
    # Standard OpenFOAM forceCoeffs columns
    columns = ["Time", "Cd", "Cd_f", "Cd_r", "Cl", "Cl_f", "Cl_r", 
               "CmPitch", "CmRoll", "CmYaw", "Cs", "Cs_f", "Cs_r"]
    df.columns = columns[:len(df.columns)]

    scaling_factor = df["Cl"].max()  # normalisation
    scaling_factor = 0.01**2 /30**2
    df["Cl"] = df["Cl"] * scaling_factor
    df["Cd"] = df["Cd"] * scaling_factor

    # Isolate steady-state regime
    steady_df = df[df["Time"] >= T_START].copy()
    print(f"\nProcessing steady regime (t >= {T_START}s)")

    # 1. Statistics
    print("\n===== PERFORMANCE STATISTICS =====")
    for coeff in ["Cd", "Cl"]:
        print(f"{coeff}: Mean = {steady_df[coeff].mean():.4f} | Std = {steady_df[coeff].std():.4f}")

    # 2. Time History Plot
    plt.figure(figsize=(10, 5))
    plt.plot(df["Time"], df[SIGNAL_NAME], label=f"Raw {SIGNAL_NAME}")
    plt.axvline(T_START, color="red", linestyle="--", label="Steady Threshold")
    plt.xlabel("Time [s]")
    plt.ylabel(SIGNAL_NAME)
    plt.title(f"{SIGNAL_NAME} Time History")
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.savefig(os.path.join(OUTPUT_DIR, f"{SIGNAL_NAME}_history.png"))

    # 3. FFT Analysis
    signal = steady_df[SIGNAL_NAME].values - steady_df[SIGNAL_NAME].mean()
    time = steady_df["Time"].values
    dt = np.mean(np.diff(time))
    N = len(signal)

    yf = fft(signal)
    xf = fftfreq(N, dt)

    # Keep positive frequencies
    pos_mask = xf > 0
    xf, yf = xf[pos_mask], yf[pos_mask]
    amplitude = 2.0 / N * np.abs(yf)

    # Dominant frequency & Strouhal
    dom_freq = xf[np.argmax(amplitude)]
    strouhal = dom_freq * L_REF / U_INF

    print("\n===== FREQUENCY ANALYSIS =====")
    print(f"Dominant Frequency: {dom_freq:.4f} Hz")
    print(f"Strouhal Number:   {strouhal:.4f}")

    # 4. FFT Plot
    plt.figure(figsize=(10, 5))
    plt.plot(xf, amplitude, color='darkblue')
    plt.xlim(0, 10 * dom_freq) # Zoom on relevant frequency range
    plt.xlabel("Frequency [Hz]")
    plt.ylabel("Amplitude")
    plt.title(f"FFT Spectrum of {SIGNAL_NAME} (St = {strouhal:.3f})")
    plt.grid(True, alpha=0.3)
    plt.savefig(os.path.join(OUTPUT_DIR, "fft_spectrum.png"))
    plt.close()

# ============================================================
# MAIN EXECUTION
# ============================================================

if __name__ == "__main__":
    print("Starting Post-Processing...")
    
    # Process convergence
    plot_residuals()
    
    # Process aerodynamic data
    process_coefficients()
    
    print("\nAll tasks completed. Check the 'plots/' folder.")